# Generated by Django 3.2.23 on 2023-12-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20231227_1051'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_deleted'], name='store_categ_is_dele_bbc986_idx'),
        ),
    ]
